name = "diff-do"
route = { pattern = "*/*", zone_name = "diff.do" }
main = "dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2022-09-23"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

workers_dev = false

[build]
command = "npm run build"
 
[build.upload]
format = "modules"

[miniflare]
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"